FROM golang:1.24 AS builder

WORKDIR /app

COPY . .
RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o user ./cmd

FROM alpine:3.21

COPY --from=builder /app/user /usr/bin/user

ENTRYPOINT ["/usr/bin/user"]